export const AUTH_USER = "AUTH_USER";
export const FETCH_INDUSTRIES = "FETCH_INDUSTRIES";
export const FETCH_SUB_INDUSTRIES = "FETCH_SUB_INDUSTRIES";
export const POST_NEW_COMPANY = "POST_NEW_COMPANY";
