export const SAVE_TOKEN = "SAVE_TOKEN";
export const SAVE_INDUSTRIES = "SAVE_INDUSTRIES";
export const SAVE_SUB_INDUSTRIES = "SAVE_SUB_INDUSTRIES";
export const FETCH_INDUSTRIES = "FETCH_INDUSTRIES";
export const FETCH_SUB_INDUSTRIES = "FETCH_SUB_INDUSTRIES";
export const POST_NEW_COMPANY = "POST_NEW_COMPANY";
export const CONFIRM_REGISTRATION = "CONFIRM_REGISTRATION";
export const SAVE_ACCOUNT_CREDENTIALS = "CONFIRM_REGISTRATION";



